### ISSUE TITLE
NPM run scripts

### ISSUE THREAD

**Issue by scottaj** [azer/npm.el#2]
Hi, I have been wanting to create an emacs package that lists and runs scripts defined in a package.json. I was about to make my own package to do it when I found this repo. 

Do you think this functionality fits within what your package is trying to accomplish? 

If so, are you open to a PR from me that will add the functionality I am describing?

**Comment by azer** [comment]
@scottaj yeah, you can add "npm run"

**Comment by scottaj** [comment]
Cool, I'll try and have something up for you to look at in the next week or so.
